<?php

// TODO: Document!
class Prack_Mime
{
	// TODO: Document!
	static function mimeType( $extension, $fallback = null )
	{
		if ( is_null( $fallback ) )
			$fallback = Prb::Str( 'application/octet-stream' );
		
		return self::mimeTypes()->fetch( $extension, $fallback );
	}
	
	// TODO: Document!
	static function mimeTypes()
	{
		static $mimeTypes = null;
		
		if ( is_null( $mimeTypes ) )
		{
			$mimeTypes = Prb::Hsh( array(
			  ".3gp"     => Prb::Str( "video/3gpp"                                      ),
			  ".a"       => Prb::Str( "application/octet-stream"                        ),
			  ".ai"      => Prb::Str( "application/postscript"                          ),
			  ".aif"     => Prb::Str( "audio/x-aiff"                                    ),
			  ".aiff"    => Prb::Str( "audio/x-aiff"                                    ),
			  ".asc"     => Prb::Str( "application/pgp-signature"                       ),
			  ".asf"     => Prb::Str( "video/x-ms-asf"                                  ),
			  ".asm"     => Prb::Str( "text/x-asm"                                      ),
			  ".asx"     => Prb::Str( "video/x-ms-asf"                                  ),
			  ".atom"    => Prb::Str( "application/atom+xml"                            ),
			  ".au"      => Prb::Str( "audio/basic"                                     ),
			  ".avi"     => Prb::Str( "video/x-msvideo"                                 ),
			  ".bat"     => Prb::Str( "application/x-msdownload"                        ),
			  ".bin"     => Prb::Str( "application/octet-stream"                        ),
			  ".bmp"     => Prb::Str( "image/bmp"                                       ),
			  ".bz2"     => Prb::Str( "application/x-bzip2"                             ),
			  ".c"       => Prb::Str( "text/x-c"                                        ),
			  ".cab"     => Prb::Str( "application/vnd.ms-cab-compressed"               ),
			  ".cc"      => Prb::Str( "text/x-c"                                        ),
			  ".chm"     => Prb::Str( "application/vnd.ms-htmlhelp"                     ),
			  ".class"   => Prb::Str( "application/octet-stream"                        ),
			  ".com"     => Prb::Str( "application/x-msdownload"                        ),
			  ".conf"    => Prb::Str( "text/plain"                                      ),
			  ".cpp"     => Prb::Str( "text/x-c"                                        ),
			  ".crt"     => Prb::Str( "application/x-x509-ca-cert"                      ),
			  ".css"     => Prb::Str( "text/css"                                        ),
			  ".csv"     => Prb::Str( "text/csv"                                        ),
			  ".cxx"     => Prb::Str( "text/x-c"                                        ),
			  ".deb"     => Prb::Str( "application/x-debian-package"                    ),
			  ".der"     => Prb::Str( "application/x-x509-ca-cert"                      ),
			  ".diff"    => Prb::Str( "text/x-diff"                                     ),
			  ".djv"     => Prb::Str( "image/vnd.djvu"                                  ),
			  ".djvu"    => Prb::Str( "image/vnd.djvu"                                  ),
			  ".dll"     => Prb::Str( "application/x-msdownload"                        ),
			  ".dmg"     => Prb::Str( "application/octet-stream"                        ),
			  ".doc"     => Prb::Str( "application/msword"                              ),
			  ".dot"     => Prb::Str( "application/msword"                              ),
			  ".dtd"     => Prb::Str( "application/xml-dtd"                             ),
			  ".dvi"     => Prb::Str( "application/x-dvi"                               ),
			  ".ear"     => Prb::Str( "application/java-archive"                        ),
			  ".eml"     => Prb::Str( "message/rfc822"                                  ),
			  ".eps"     => Prb::Str( "application/postscript"                          ),
			  ".exe"     => Prb::Str( "application/x-msdownload"                        ),
			  ".f"       => Prb::Str( "text/x-fortran"                                  ),
			  ".f77"     => Prb::Str( "text/x-fortran"                                  ),
			  ".f90"     => Prb::Str( "text/x-fortran"                                  ),
			  ".flv"     => Prb::Str( "video/x-flv"                                     ),
			  ".for"     => Prb::Str( "text/x-fortran"                                  ),
			  ".gem"     => Prb::Str( "application/octet-stream"                        ),
			  ".gemspec" => Prb::Str( "text/x-script.ruby"                              ),
			  ".gif"     => Prb::Str( "image/gif"                                       ),
			  ".gz"      => Prb::Str( "application/x-gzip"                              ),
			  ".h"       => Prb::Str( "text/x-c"                                        ),
			  ".htc"     => Prb::Str( "text/x-component"                                ),
			  ".hh"      => Prb::Str( "text/x-c"                                        ),
			  ".htm"     => Prb::Str( "text/html"                                       ),
			  ".html"    => Prb::Str( "text/html"                                       ),
			  ".ico"     => Prb::Str( "image/vnd.microsoft.icon"                        ),
			  ".ics"     => Prb::Str( "text/calendar"                                   ),
			  ".ifb"     => Prb::Str( "text/calendar"                                   ),
			  ".iso"     => Prb::Str( "application/octet-stream"                        ),
			  ".jar"     => Prb::Str( "application/java-archive"                        ),
			  ".java"    => Prb::Str( "text/x-java-source"                              ),
			  ".jnlp"    => Prb::Str( "application/x-java-jnlp-file"                    ),
			  ".jpeg"    => Prb::Str( "image/jpeg"                                      ),
			  ".jpg"     => Prb::Str( "image/jpeg"                                      ),
			  ".js"      => Prb::Str( "application/javascript"                          ),
			  ".json"    => Prb::Str( "application/json"                                ),
			  ".log"     => Prb::Str( "text/plain"                                      ),
			  ".m3u"     => Prb::Str( "audio/x-mpegurl"                                 ),
			  ".m4v"     => Prb::Str( "video/mp4"                                       ),
			  ".man"     => Prb::Str( "text/troff"                                      ),
			  ".manifest"=> Prb::Str( "text/cache-manifest"                             ),
			  ".mathml"  => Prb::Str( "application/mathml+xml"                          ),
			  ".mbox"    => Prb::Str( "application/mbox"                                ),
			  ".mdoc"    => Prb::Str( "text/troff"                                      ),
			  ".me"      => Prb::Str( "text/troff"                                      ),
			  ".mid"     => Prb::Str( "audio/midi"                                      ),
			  ".midi"    => Prb::Str( "audio/midi"                                      ),
			  ".mime"    => Prb::Str( "message/rfc822"                                  ),
			  ".mml"     => Prb::Str( "application/mathml+xml"                          ),
			  ".mng"     => Prb::Str( "video/x-mng"                                     ),
			  ".mov"     => Prb::Str( "video/quicktime"                                 ),
			  ".mp3"     => Prb::Str( "audio/mpeg"                                      ),
			  ".mp4"     => Prb::Str( "video/mp4"                                       ),
			  ".mp4v"    => Prb::Str( "video/mp4"                                       ),
			  ".mpeg"    => Prb::Str( "video/mpeg"                                      ),
			  ".mpg"     => Prb::Str( "video/mpeg"                                      ),
			  ".ms"      => Prb::Str( "text/troff"                                      ),
			  ".msi"     => Prb::Str( "application/x-msdownload"                        ),
			  ".odp"     => Prb::Str( "application/vnd.oasis.opendocument.presentation" ),
			  ".ods"     => Prb::Str( "application/vnd.oasis.opendocument.spreadsheet"  ),
			  ".odt"     => Prb::Str( "application/vnd.oasis.opendocument.text"         ),
			  ".ogg"     => Prb::Str( "application/ogg"                                 ),
			  ".ogv"     => Prb::Str( "video/ogg"                                       ),
			  ".p"       => Prb::Str( "text/x-pascal"                                   ),
			  ".pas"     => Prb::Str( "text/x-pascal"                                   ),
			  ".pbm"     => Prb::Str( "image/x-portable-bitmap"                         ),
			  ".pdf"     => Prb::Str( "application/pdf"                                 ),
			  ".pem"     => Prb::Str( "application/x-x509-ca-cert"                      ),
			  ".pgm"     => Prb::Str( "image/x-portable-graymap"                        ),
			  ".pgp"     => Prb::Str( "application/pgp-encrypted"                       ),
			  ".pkg"     => Prb::Str( "application/octet-stream"                        ),
			  ".pl"      => Prb::Str( "text/x-script.perl"                              ),
			  ".pm"      => Prb::Str( "text/x-script.perl-module"                       ),
			  ".png"     => Prb::Str( "image/png"                                       ),
			  ".pnm"     => Prb::Str( "image/x-portable-anymap"                         ),
			  ".ppm"     => Prb::Str( "image/x-portable-pixmap"                         ),
			  ".pps"     => Prb::Str( "application/vnd.ms-powerpoint"                   ),
			  ".ppt"     => Prb::Str( "application/vnd.ms-powerpoint"                   ),
			  ".ps"      => Prb::Str( "application/postscript"                          ),
			  ".psd"     => Prb::Str( "image/vnd.adobe.photoshop"                       ),
			  ".py"      => Prb::Str( "text/x-script.python"                            ),
			  ".qt"      => Prb::Str( "video/quicktime"                                 ),
			  ".ra"      => Prb::Str( "audio/x-pn-realaudio"                            ),
			  ".rake"    => Prb::Str( "text/x-script.ruby"                              ),
			  ".ram"     => Prb::Str( "audio/x-pn-realaudio"                            ),
			  ".rar"     => Prb::Str( "application/x-rar-compressed"                    ),
			  ".rb"      => Prb::Str( "text/x-script.ruby"                              ),
			  ".rdf"     => Prb::Str( "application/rdf+xml"                             ),
			  ".roff"    => Prb::Str( "text/troff"                                      ),
			  ".rpm"     => Prb::Str( "application/x-redhat-package-manager"            ),
			  ".rss"     => Prb::Str( "application/rss+xml"                             ),
			  ".rtf"     => Prb::Str( "application/rtf"                                 ),
			  ".ru"      => Prb::Str( "text/x-script.ruby"                              ),
			  ".s"       => Prb::Str( "text/x-asm"                                      ),
			  ".sgm"     => Prb::Str( "text/sgml"                                       ),
			  ".sgml"    => Prb::Str( "text/sgml"                                       ),
			  ".sh"      => Prb::Str( "application/x-sh"                                ),
			  ".sig"     => Prb::Str( "application/pgp-signature"                       ),
			  ".snd"     => Prb::Str( "audio/basic"                                     ),
			  ".so"      => Prb::Str( "application/octet-stream"                        ),
			  ".svg"     => Prb::Str( "image/svg+xml"                                   ),
			  ".svgz"    => Prb::Str( "image/svg+xml"                                   ),
			  ".swf"     => Prb::Str( "application/x-shockwave-flash"                   ),
			  ".t"       => Prb::Str( "text/troff"                                      ),
			  ".tar"     => Prb::Str( "application/x-tar"                               ),
			  ".tbz"     => Prb::Str( "application/x-bzip-compressed-tar"               ),
			  ".tcl"     => Prb::Str( "application/x-tcl"                               ),
			  ".tex"     => Prb::Str( "application/x-tex"                               ),
			  ".texi"    => Prb::Str( "application/x-texinfo"                           ),
			  ".texinfo" => Prb::Str( "application/x-texinfo"                           ),
			  ".text"    => Prb::Str( "text/plain"                                      ),
			  ".tif"     => Prb::Str( "image/tiff"                                      ),
			  ".tiff"    => Prb::Str( "image/tiff"                                      ),
			  ".torrent" => Prb::Str( "application/x-bittorrent"                        ),
			  ".tr"      => Prb::Str( "text/troff"                                      ),
			  ".txt"     => Prb::Str( "text/plain"                                      ),
			  ".vcf"     => Prb::Str( "text/x-vcard"                                    ),
			  ".vcs"     => Prb::Str( "text/x-vcalendar"                                ),
			  ".vrml"    => Prb::Str( "model/vrml"                                      ),
			  ".war"     => Prb::Str( "application/java-archive"                        ),
			  ".wav"     => Prb::Str( "audio/x-wav"                                     ),
			  ".webm"    => Prb::Str( "video/webm"                                      ),
			  ".wma"     => Prb::Str( "audio/x-ms-wma"                                  ),
			  ".wmv"     => Prb::Str( "video/x-ms-wmv"                                  ),
			  ".wmx"     => Prb::Str( "video/x-ms-wmx"                                  ),
			  ".wrl"     => Prb::Str( "model/vrml"                                      ),
			  ".wsdl"    => Prb::Str( "application/wsdl+xml"                            ),
			  ".xbm"     => Prb::Str( "image/x-xbitmap"                                 ),
			  ".xhtml"   => Prb::Str( "application/xhtml+xml"                           ),
			  ".xls"     => Prb::Str( "application/vnd.ms-excel"                        ),
			  ".xml"     => Prb::Str( "application/xml"                                 ),
			  ".xpm"     => Prb::Str( "image/x-xpixmap"                                 ),
			  ".xsl"     => Prb::Str( "application/xml"                                 ),
			  ".xslt"    => Prb::Str( "application/xslt+xml"                            ),
			  ".yaml"    => Prb::Str( "text/yaml"                                       ),
			  ".yml"     => Prb::Str( "text/yaml"                                       ),
			  ".zip"     => Prb::Str( "application/zip"                                 )
			) );
		}
		
		return $mimeTypes;
	}
}
